# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  major: 1
  # define minor as a counter with the prefix as variable major, and seed as 100.
  minor: $[counter(variables['major'], 100)]

steps:
- bash: echo $(minor)

# stages:
# - stage: A
#   jobs:
#   - job: A1
#   - job: A2

# - stage: B
#   jobs:
#   - job: B1
#   - job: B2
#   condition: 
  
# steps:
# - task: TerraformInstaller@0
#   inputs:
#     terraformVersion: '1.3.8'



# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
